"""empty message

Revision ID: 7e4c9ae9c35b
Revises: b6a86c4feefb
Create Date: 2023-09-19 16:42:00.389073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4c9ae9c35b'
down_revision = 'b6a86c4feefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserved', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
